name: clase6
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dise침o (Volvemos a la versi칩n 8 para compatibilidad con tu Flutter nuevo)
  flex_color_scheme: ^8.3.1
  google_fonts: ^6.3.2
  
  # Firebase (Versiones Est치ndar)
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  google_sign_in: ^7.2.0 # Mantenemos esta que es la que te funcion칩 bien

  image_picker: ^0.8.7+5
  firebase_storage: ^11.7.7

  
  # Mapas
  flutter_map: ^6.1.0 
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  url_launcher: ^6.3.2
  web: ^0.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/LogoApp.png
    - assets/images/LogoAppOut.png